Build and Test

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,6 +1,3 @@
-# This workflow will build a golang project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
-
 name: Go
 
 env:
@@ -13,7 +10,6 @@ on:
     branches: [ "main" ]
 
 jobs:
-
   build:
     runs-on: ubuntu-latest
 
@@ -30,14 +26,24 @@ jobs:
         cache: true
 
     - name: Revive Action
-      run: morphy2k/revive-action@v2.4.1
+      uses: morphy2k/revive-action@v2.4.1
 
-    - name: Run StaticCheck
-      run: dominikh/staticcheck-action@v1.3.0
+    - name: Staticcheck
+      uses: dominikh/staticcheck-action@v1.3.0
 
     - name: Build
-      run: go build -v ./...
+      run: |
+        go mod download
+        go install gotest.tools/gotestsum@latest
 
     - name: Test
-      run: go test -v ./...
-      
+      run: |
+        gotestsum --format=standard-verbose --junitfile=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
